CC = gcc
DEPS = src/main.h
OBJ_M = utils.o main.o
OBJ_A = utils.o app.o
BINARIES = app main
SOURCES = src/app.c src/main.c src/utils.c
TARGETS = $(BINARIES)

CFLAGS += -g -Wall -DDEBUG
LIBS = -lssl -lcrypto -lsqlite3 -lbase58 -lsodium -lev 
# LIBS += -ldmalloc
CXXFLAGS += $(CFLAGS)

## Tests
ROUND_TIME := 10
REJECT_PRC := 0
PEER_COUNT := 10 20 30 50 90
OPTIMAL_NEXT := 2

## Format of test string t-[proto][mode]-[next]-[prev]-[peers]
UDP_S1_JOBS := $(addprefix t-udps-${OPTIMAL_NEXT}-1-,${PEER_COUNT})
UDP_S2_JOBS := $(addprefix t-udps-${OPTIMAL_NEXT}-2-,${PEER_COUNT})
UDP_S3_JOBS := $(addprefix t-udps-${OPTIMAL_NEXT}-3-,${PEER_COUNT})
UDP_S4_JOBS := $(addprefix t-udps-${OPTIMAL_NEXT}-4-,${PEER_COUNT})
UDP_N1_JOBS := $(addprefix t-udpn-${OPTIMAL_NEXT}-1-,${PEER_COUNT})
UDP_N2_JOBS := $(addprefix t-udpn-${OPTIMAL_NEXT}-2-,${PEER_COUNT})
UDP_N3_JOBS := $(addprefix t-udpn-${OPTIMAL_NEXT}-3-,${PEER_COUNT})
UDP_N4_JOBS := $(addprefix t-udpn-${OPTIMAL_NEXT}-4-,${PEER_COUNT})
TCP_S1_JOBS := $(addprefix t-tcps-${OPTIMAL_NEXT}-1-,${PEER_COUNT})
TCP_S2_JOBS := $(addprefix t-tcps-${OPTIMAL_NEXT}-2-,${PEER_COUNT})
TCP_S3_JOBS := $(addprefix t-tcps-${OPTIMAL_NEXT}-3-,${PEER_COUNT})
TCP_S4_JOBS := $(addprefix t-tcps-${OPTIMAL_NEXT}-4-,${PEER_COUNT})
TCP_N1_JOBS := $(addprefix t-tcpn-${OPTIMAL_NEXT}-1-,${PEER_COUNT})
TCP_N2_JOBS := $(addprefix t-tcpn-${OPTIMAL_NEXT}-2-,${PEER_COUNT})
TCP_N3_JOBS := $(addprefix t-tcpn-${OPTIMAL_NEXT}-3-,${PEER_COUNT})
TCP_N4_JOBS := $(addprefix t-tcpn-${OPTIMAL_NEXT}-4-,${PEER_COUNT})

all: $(BINARIES)

%.o: src/%.c 
	  $(CC) -c -o $@ $< $(CFLAGS)

main: $(OBJ_M)
	  $(CC) -o $@ $^ $(CFLAGS) $(LIBS)

app: $(OBJ_A)
	  $(CC) -o $@ $^ $(CFLAGS) $(LIBS) 

cleano:
	  rm -f *.o

clean: cleano
	  rm -f $(TARGETS) *.bak *.db *.log

# UDP LIKE-AND-SHARE
t-udps-1-1-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-1-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-1-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-1-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-1-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-1-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-1-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-1-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-1-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-1-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-1-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-1-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-1-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-1-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-1-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-1-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-1-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-1-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-1-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-1-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-2-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-2-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-2-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-2-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-2-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-2-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-2-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-2-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-2-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-2-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-2-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-2-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-2-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-2-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-2-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-2-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-2-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-2-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-2-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-2-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-3-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-3-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-3-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-3-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-3-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-3-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-3-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-3-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-3-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-3-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-3-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-3-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-3-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-3-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-3-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-3-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-3-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-3-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-3-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-3-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-4-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-4-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-4-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-4-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-1-4-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-4-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-4-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-4-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-4-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-2-4-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-4-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-4-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-4-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-4-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-3-4-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-4-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-4-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-4-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-4-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udps-4-4-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}

# UDP NORMAL
t-udpn-1-1-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-1-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-1-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-1-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-1-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-1-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-1-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-1-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-1-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-1-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-1-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-1-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-1-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-1-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-1-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-1-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-1-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-1-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-1-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-1-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-2-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-2-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-2-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-2-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-2-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-2-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-2-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-2-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-2-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-2-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-2-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-2-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-2-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-2-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-2-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-2-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-2-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-2-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-2-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-2-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-3-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-3-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-3-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-3-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-3-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-3-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-3-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-3-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-3-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-3-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-3-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-3-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-3-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-3-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-3-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-3-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-3-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-3-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-3-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-3-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-4-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-4-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-4-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-4-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-1-4-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-4-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-4-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-4-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-4-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-2-4-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-4-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-4-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-4-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-4-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-3-4-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-4-10: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-4-20: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-4-30: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-4-50: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-udpn-4-4-90: ;PATH=.:$${PATH} main --proto 0 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}

# TCP LIKE-AND-SHARE
t-tcps-1-1-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-1-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-1-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-1-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-1-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-1-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-1-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-1-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-1-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-1-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-1-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-1-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-1-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-1-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-1-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-1-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-1-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-1-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-1-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-1-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-2-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-2-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-2-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-2-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-2-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-2-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-2-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-2-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-2-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-2-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-2-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-2-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-2-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-2-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-2-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-2-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-2-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-2-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-2-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-2-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-3-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-3-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-3-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-3-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-3-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-3-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-3-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-3-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-3-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-3-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-3-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-3-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-3-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-3-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-3-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-3-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-3-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-3-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-3-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-3-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-4-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-4-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-4-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-4-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-1-4-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-4-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-4-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-4-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-4-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-2-4-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-4-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-4-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-4-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-4-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-3-4-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-4-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-4-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-4-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-4-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcps-4-4-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 1 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}

# TCP NORMAL
t-tcpn-1-1-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-1-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-1-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-1-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-1-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-1-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-1-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-1-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-1-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-1-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-1-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-1-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-1-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-1-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-1-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-1-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-1-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-1-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-1-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-1-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 1 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-2-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-2-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-2-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-2-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-2-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-2-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-2-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-2-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-2-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-2-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-2-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-2-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-2-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-2-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-2-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-2-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-2-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-2-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-2-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-2-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 2 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-3-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-3-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-3-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-3-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-3-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-3-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-3-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-3-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-3-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-3-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-3-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-3-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-3-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-3-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-3-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-3-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-3-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-3-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-3-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-3-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 3 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-4-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-4-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-4-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-4-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-1-4-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 1 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-4-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-4-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-4-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-4-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-2-4-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 2 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-4-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-4-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-4-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-4-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-3-4-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 3 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-4-10: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 10 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-4-20: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 20 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-4-30: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 30 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-4-50: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 50 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}
t-tcpn-4-4-90: ;PATH=.:$${PATH} main --proto 1 --gossip-mode 0 --number-of-peers 90 --previous-peer-number 4 --next-peer-number 4 --round-time ${ROUND_TIME} --reject-prc ${REJECT_PRC}

test-udps: ${UDP_S2_JOBS}; echo "$@ ok"
test-udpn: ${UDP_N2_JOBS}; echo "$@ ok"
test-tcps: ${TCP_S2_JOBS}; echo "$@ ok"
test-tcpn: ${TCP_N2_JOBS}; echo "$@ ok"
